
name: Bitasmbl Validation

on:
  push:
    branches: [main]

jobs:
  scaffold:
    if: github.event.head_commit.message == 'bitasmbl:init'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Frontend
        run: npx create-next-app@latest ./frontend
      - name: Commit scaffold
        run: |
          git config user.name "he1snber8"
          git config user.email "lukakhajavelidze@yahoo.com"
          git add .
          git commit -m "bitasmbl: scaffold project"
          git push

